### ISSUE TITLE
[feature] ability to create cloud sql database

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#190]
So, I'm trying to use the CLI tool to create a database on Google Cloud SQL and it is failing because `set session_replication_role = 'replica';` is only available to superusers and GCSQL [doesn't allow any commands that require superusers](https://cloud.google.com/sql/docs/postgres/features). Lovely. Can you make it a flag to turn it off?

```
mikro-orm schema:create -r --fk-checks=false
Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail
mikro-orm schema:create

Create database schema based on current metadata

Options:
  -r, --run      Runs queries                                          [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  --fk-checks    Do not skip foreign key checks                        [boolean]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

error: permission denied to set parameter "session_replication_role"
    at Connection.parseE (/functions/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/functions/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/functions/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:209:13)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 121,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'guc.c',
  line: '6329',
  routine: 'set_config_option'
}
```

**Comment by B4nan** [comment]
Use just `--fk-checks`, true means that those statements won't be there (fk checks are allowed), false (default) means all queries will be wrapped between those FK statements.

**Comment by lookfirst** [comment]
Oh, I had it inverse. Started reading through the code but got distracted by dinner. =) Thanks man!

**Comment by MehdiHamidi** [comment]
@B4nan Is there a way to do this using SchemaGenerator programmatically?

**Comment by B4nan** [comment]
https://mikro-orm.io/docs/schema-generator#using-schemagenerator-programmatically

**Comment by MehdiHamidi** [comment]
@B4nan Thanks for the quick response, but I meant using the `--fk-checks`. I'm using Google SQL too and I'm having the same issue with `set session_replication_role = 'replica';`

**Comment by B4nan** [comment]
There is a `wrap` parameter, pass `false` there to omit those `session_replication_role` queries. I think I will change the default, it should be no longer needed as we now use the `CommitOrderCalculator` to get the right order of entities in schema generator too.

**Comment by MehdiHamidi** [comment]
That did it, thank you!

**Comment by MehdiHamidi** [comment]
@B4nan Sorry to bother you again, is this possible for Migrator too? When running `migrator.up()` I'm getting the same error and I can't seem to find the same `wrap `parameter. I'm new to TS so I might not be looking in the right places

**Comment by MehdiHamidi** [comment]
Nevermind I got it!  
`migrations: {
path: ORM_MIGRATIONS_PATH,
        disableForeignKeys: false}`

**Comment by cpannwitz** [comment]
Got the same error this morning, running migrations via `migration.up()` on Heroku PostgresQL.
Fixed by `disableForeignKeys: false` as mentioned by @MehdiHamidi :)

**Comment by idkjs** [comment]
I've run the example on this repo:https://github.com/driescroons/mikro-orm-graphql-example/issues/3#issue-744600923 and I'm still getting this. I am on pg 13. Any ideas would be greatly appreciated. Thank you.

**Comment by dylvaz** [comment]
> Nevermind I got it!
> `migrations: { path: ORM_MIGRATIONS_PATH, disableForeignKeys: false}`

@MehdiHamidi This worked for me! Do you mind explaining how this fixes the issue?

**Comment by jbovone** [comment]
I don't understand. But it worked for me.

**Comment by drackp2m** [comment]
I imagine that what I am going to explain now, does not apply to production environments where there are some limitations, however, I am going to comment it in case it happens to someone during development (as it was my case) and it helps to solve it. <3

Had the same problem when trying to create a second DB in my main DB Docker container (until now I was starting a separate new container, exclusively for tests).

Then, I encountered this error during the process of running migrations and after [some internet searches](https://stackoverflow.com/a/75380655), run the statement:

```sql
GRANT SET ON PARAMETER session_replication_role TO <username>;
```

Stopped giving the error!!!
