### ISSUE TITLE
MongoDB ISODates are erased when inside a JSON property

### ISSUE THREAD

**Issue by alexandre-abrioux** [mikro-orm/mikro-orm#6078]
### Describe the bug

This is a follow-up to #6076 (sorry again for the first failed reproduction test case!)

This regression was introduced in v6.3.11 and probably linked to https://github.com/mikro-orm/mikro-orm/commit/55df57ff1aa84e5d45188d849ba09e91ae6d3642 (https://github.com/mikro-orm/mikro-orm/issues/6050).

When persisting a date inside a JSON property with the MongoDB driver, it is correctly saved as an ISODate.

When retrieving the document, the MongoDB driver returns an ISODates object (BSON date), but MikroORM hydration erases its content and prototype. The date is instead hydrated as an empty object `{}`.

### Reproduction

Here is a test case: https://github.com/alexandre-abrioux/mikro-orm-issues/blob/iss-6078/src/example.test.ts

### What driver are you using?

@mikro-orm/mongodb

### MikroORM version

6.3.11

### Node.js version

22.4.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This actually sounds like a jest issue, the `structuredClone` on node level works fine and produces `Date` objects, but when done inside a jest test, those are no longer real Date objects (`instanceof Date` fails to recognize them).

https://github.com/jestjs/jest/issues/14947

I wonder if you also found out about this inside a jest test or in a production environment, as I believe things should work fine outside of jest (or some other test runner).

**Comment by B4nan** [comment]
I've fixed it by checking the constructor name as a fallback for dates, let's see if that will be enough, please the dev version.

Note that your test shows something else than what you are describing, the problem is storing the value, not reading it, it's already written wrongly into the database.

**Comment by alexandre-abrioux** [comment]
Thanks, @B4nan, I've tested the dev version, and that fixed it 🙂

**Comment by alexandre-abrioux** [comment]
Unfortunately, we still have a similar issue with ObjectIDs 😕
I've made a PR to bootstrap the fix: https://github.com/mikro-orm/mikro-orm/pull/6091 ; let me know what you think!
